GET http://localhost:5000/admin/createaccount/

###

POST http://localhost:5000/admin/createaccount/
Content-Type: application/json

{
    "email":"cezarmocanu2014@gmail.com",
    "password":"123456"
}

###
POST http://localhost:5000/admin/login/
Content-Type: application/json

{
    "email":"cezarmocanu2014@gmail.com",
    "password":"123456"
}

###

POST http://localhost:5000/admin/checktoken/
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE1ODczMDMyNzIsImV4cCI6MTU4NzMwMzI4N30.sU74JMYWBWsN2UnOlj7Ig7RGE8vmHHghS0H7zOeROf8"
}

###

POST http://localhost:5000/api/categories/
Content-Type: application/json

{
    "data":"data"
}
